
[31mStart to train the network

[5/5] Loss: 0.7834: 100%|====================| 5/5 [00:05<00:00,  1.01s/it]
[34mEpoch [1/5]
     Train Loss: 0.8045 - Validation Loss: 0.1558
     Train LossMSE: 0.1647 - Validation LossMSE: 0.1429
     Train PSNR: 7.8978 - Validation PSNR: 8.4533
     Train SSIM: 0.0729 - Validation SSIM: 0.2480
[32m     New Best Validation PSNR: 8.4533 


[5/5] Loss: 0.6144: 100%|====================| 5/5 [00:04<00:00,  1.08it/s]
Training  0%|                    | 0/5 [00:00<?, ?it/s]
[34mEpoch [2/5]
     Train Loss: 0.6766 - Validation Loss: 187.4270
     Train LossMSE: 0.0506 - Validation LossMSE: 0.0338
     Train PSNR: 14.1025 - Validation PSNR: 14.7247
     Train SSIM: 0.3633 - Validation SSIM: 0.4862


[5/5] Loss: 0.5422: 100%|====================| 5/5 [00:04<00:00,  1.08it/s]
Training  0%|                    | 0/5 [00:00<?, ?it/s]
[34mEpoch [3/5]
     Train Loss: 0.5678 - Validation Loss: 56.1979
     Train LossMSE: 0.0151 - Validation LossMSE: 0.0316
     Train PSNR: 18.2539 - Validation PSNR: 15.0074
     Train SSIM: 0.3301 - Validation SSIM: 0.1676

[5/5] Loss: 0.5048: 100%|====================| 5/5 [00:04<00:00,  1.09it/s]
Training  0%|                    | 0/5 [00:00<?, ?it/s]
[34mEpoch [4/5]
     Train Loss: 0.5190 - Validation Loss: 12.5617
     Train LossMSE: 0.0134 - Validation LossMSE: 0.0270
     Train PSNR: 18.7471 - Validation PSNR: 15.6919
     Train SSIM: 0.2064 - Validation SSIM: 0.1380

[5/5] Loss: 0.5001: 100%|====================| 5/5 [00:04<00:00,  1.08it/s]
[34mEpoch [5/5]
     Train Loss: 0.5002 - Validation Loss: 2.9523
     Train LossMSE: 0.0135 - Validation LossMSE: 0.0191
     Train PSNR: 18.6865 - Validation PSNR: 17.1907
     Train SSIM: 0.1928 - Validation SSIM: 0.1603
[32m     New Best Validation PSNR: 17.1907 
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\main.py", line 86, in call_training
    myNet.evaluate(resultPath = resultPath, printPrediction = True)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\models\RegularizedEmbeddingClass.py", line 239, in evaluate
    allInputs, allPreds, allLabels, allMasks = self.getPrediction(self.testlDataLoader, resultPath)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\models\RegularizedEmbeddingClass.py", line 205, in getPrediction
    for (corrupted, image, mask, label) in dataLoader:
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\datasets\dataLoader.py", line 53, in __getitem__
    folder, file = self.imgList[idx].split('/')[-2], self.imgList[idx].split('/')[-1]
IndexError: list index out of range
[31mThe network is trained
>>  E:\mvtec_anomaly_detection\runtime\test\defective\000.png
>>  ['E:\\mvtec_anomaly_detection\\runtime\\test\\defective\\000.png']