
[31mStart to train the network

[5/5] Loss: 0.7832: 100%|====================| 5/5 [00:05<00:00,  1.02s/it]
[34mEpoch [1/5]
     Train Loss: 0.8045 - Validation Loss: 0.1558
     Train LossMSE: 0.1647 - Validation LossMSE: 0.1429
     Train PSNR: 7.8979 - Validation PSNR: 8.4533
     Train SSIM: 0.0729 - Validation SSIM: 0.2480
[32m     New Best Validation PSNR: 8.4533 

[5/5] Loss: 0.6141: 100%|====================| 5/5 [00:04<00:00,  1.08it/s]
[34mEpoch [2/5]
     Train Loss: 0.6765 - Validation Loss: 180.6153
     Train LossMSE: 0.0504 - Validation LossMSE: 0.0334
     Train PSNR: 14.1294 - Validation PSNR: 14.7701
     Train SSIM: 0.3645 - Validation SSIM: 0.4852
[32m     New Best Validation PSNR: 14.7701 


[5/5] Loss: 0.5422: 100%|====================| 5/5 [00:04<00:00,  1.11it/s]
[34mEpoch [3/5]
     Train Loss: 0.5676 - Validation Loss: 53.4809
     Train LossMSE: 0.0151 - Validation LossMSE: 0.0316
     Train PSNR: 18.2597 - Validation PSNR: 15.0021
     Train SSIM: 0.3302 - Validation SSIM: 0.1717
[32m     New Best Validation PSNR: 15.0021 

[5/5] Loss: 0.5049: 100%|====================| 5/5 [00:04<00:00,  1.06it/s]
[34mEpoch [4/5]
     Train Loss: 0.5192 - Validation Loss: 12.1741
     Train LossMSE: 0.0134 - Validation LossMSE: 0.0275
     Train PSNR: 18.7439 - Validation PSNR: 15.6080
     Train SSIM: 0.2059 - Validation SSIM: 0.1421
[32m     New Best Validation PSNR: 15.6080 

[5/5] Loss: 0.5003: 100%|====================| 5/5 [00:04<00:00,  1.07it/s]
[34mEpoch [5/5]
     Train Loss: 0.5005 - Validation Loss: 2.8671
     Train LossMSE: 0.0136 - Validation LossMSE: 0.0195
     Train PSNR: 18.6717 - Validation PSNR: 17.1152
     Train SSIM: 0.1925 - Validation SSIM: 0.1622
[32m     New Best Validation PSNR: 17.1152 
[31mThe network is trained
>>  E:\mvtec_anomaly_detection\runtime\test\defective\000.png
>>  ('E:\\mvtec_anomaly_detection\\runtime\\test\\defective', '000.png')
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\jorge\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\main.py", line 86, in call_training
    myNet.evaluate(resultPath = resultPath, printPrediction = True)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\models\RegularizedEmbeddingClass.py", line 239, in evaluate
    allInputs, allPreds, allLabels, allMasks = self.getPrediction(self.testlDataLoader, resultPath)
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\models\RegularizedEmbeddingClass.py", line 205, in getPrediction
    for (corrupted, image, mask, label) in dataLoader:
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\dataloader.py", line 631, in __next__
    data = self._next_data()
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\Python\AnomalyDetection-PyTorch\anDetec_env\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Code\Python\AnomalyDetection-PyTorch\src\datasets\dataLoader.py", line 62, in __getitem__
    mask     = np.expand_dims(cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY),-1)
cv2.error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'